### ISSUE TITLE
Breaking Rails 5 belongs_to_required_by_default 

### ISSUE THREAD

**Issue by bradlis7** [fnando/normalize_attributes#3]
When this is enabled, it breaks changing the line in new_framework_defaults.rb:

    Rails.application.config.active_record.belongs_to_required_by_default = true

Here are some other resources showing what's going on.

https://stackoverflow.com/a/39153224/179311
https://github.com/CanCanCommunity/cancancan/issues/342

My workaround is to use `gem 'normalize_attributes', require: false` in Gemfile, and this code in config/application.rb so that it loads it after active_record is loaded:

    class Application < Rails::Application
      ActiveSupport.on_load(:active_record) do
        require 'normalize_attributes'
      end
    end

**Comment by fnando** [comment]
It just took me 2 years to work on this. I'm deeply sorry about this.

Just released v0.3.0 which uses `ActiveSupport.on_load` like you described.
